// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Home → SiggaNav*
 */
export interface HomeDocumentDataSigganavItem {
  /**
   * sigga_hlekkir field in *Home → SiggaNav*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: home.sigganav[].sigga_hlekkir
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  sigga_hlekkir: prismic.ContentRelationshipField<"sigga">;
}

/**
 * Item in *Home → Skipulags_nav*
 */
export interface HomeDocumentDataSkipulagsNavItem {
  /**
   * skipulag_hlekkir field in *Home → Skipulags_nav*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: home.skipulags_nav[].skipulag_hlekkir
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  skipulag_hlekkir: prismic.ContentRelationshipField<"skipulagsradgjof">;
}

/**
 * Item in *Home → Rannsoknir*
 */
export interface HomeDocumentDataRannsoknirItem {
  /**
   * rannsoknir_hlekkir field in *Home → Rannsoknir*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: home.rannsoknir[].rannsoknir_hlekkir
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  rannsoknir_hlekkir: prismic.ContentRelationshipField<"rannsoknir">;
}

type HomeDocumentDataSlicesSlice = ListSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * SiggaNav field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.sigganav[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  sigganav: prismic.GroupField<Simplify<HomeDocumentDataSigganavItem>>;

  /**
   * Skipulags_nav field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.skipulags_nav[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  skipulags_nav: prismic.GroupField<Simplify<HomeDocumentDataSkipulagsNavItem>>;

  /**
   * Rannsoknir field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.rannsoknir[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  rannsoknir: prismic.GroupField<Simplify<HomeDocumentDataRannsoknirItem>>;

  /**
   * Teksti field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Sigríður Kristjánsdóttir
   * - **API ID Path**: home.teksti
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  teksti: prismic.RichTextField;

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Item in *MainNav → egveitekkert*
 */
export interface MainnavDocumentDataEgveitekkertItem {
  /**
   * what field in *MainNav → egveitekkert*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: mainnav.egveitekkert[].what
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  what: prismic.LinkToMediaField;
}

/**
 * Content for MainNav documents
 */
interface MainnavDocumentData {
  /**
   * egveitekkert field in *MainNav*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: mainnav.egveitekkert[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  egveitekkert: prismic.GroupField<
    Simplify<MainnavDocumentDataEgveitekkertItem>
  >;
}

/**
 * MainNav document from Prismic
 *
 * - **API ID**: `mainnav`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MainnavDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MainnavDocumentData>,
    "mainnav",
    Lang
  >;

type RannsoknirDocumentDataSlicesSlice = TextSSlice | FrameSlice;

/**
 * Content for Rannsóknir documents
 */
interface RannsoknirDocumentData {
  /**
   * Teksti field in *Rannsóknir*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rannsoknir.teksti
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  teksti: prismic.RichTextField;

  /**
   * Slice Zone field in *Rannsóknir*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: rannsoknir.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<RannsoknirDocumentDataSlicesSlice> /**
   * Meta Description field in *Rannsóknir*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: rannsoknir.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Rannsóknir*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: rannsoknir.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Rannsóknir*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: rannsoknir.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Rannsóknir document from Prismic
 *
 * - **API ID**: `rannsoknir`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RannsoknirDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<RannsoknirDocumentData>,
    "rannsoknir",
    Lang
  >;

type SiggaDocumentDataSlicesSlice = TekkiSlice | TextSSlice;

/**
 * Content for Sigga documents
 */
interface SiggaDocumentData {
  /**
   * teksti field in *Sigga*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sigga.teksti
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  teksti: prismic.RichTextField;

  /**
   * Slice Zone field in *Sigga*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: sigga.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SiggaDocumentDataSlicesSlice> /**
   * Meta Description field in *Sigga*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: sigga.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Sigga*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sigga.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Sigga*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: sigga.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Sigga document from Prismic
 *
 * - **API ID**: `sigga`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SiggaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<SiggaDocumentData>, "sigga", Lang>;

type SkipulagsradgjofDocumentDataSlicesSlice = TextSSlice | AlternateGridSlice;

/**
 * Content for Skipulagráðgjöf documents
 */
interface SkipulagsradgjofDocumentData {
  /**
   * Teksti field in *Skipulagráðgjöf*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skipulagsradgjof.teksti
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  teksti: prismic.RichTextField;

  /**
   * Slice Zone field in *Skipulagráðgjöf*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: skipulagsradgjof.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SkipulagsradgjofDocumentDataSlicesSlice> /**
   * Meta Description field in *Skipulagráðgjöf*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: skipulagsradgjof.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Skipulagráðgjöf*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: skipulagsradgjof.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Skipulagráðgjöf*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: skipulagsradgjof.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Skipulagráðgjöf document from Prismic
 *
 * - **API ID**: `skipulagsradgjof`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SkipulagsradgjofDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SkipulagsradgjofDocumentData>,
    "skipulagsradgjof",
    Lang
  >;

export type AllDocumentTypes =
  | HomeDocument
  | MainnavDocument
  | RannsoknirDocument
  | SiggaDocument
  | SkipulagsradgjofDocument;

/**
 * Primary content in *AlternateGrid → Primary*
 */
export interface AlternateGridSliceDefaultPrimary {
  /**
   * eyebrowHeadline field in *AlternateGrid → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: alternate_grid.primary.eyebrowHeadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrowHeadline: prismic.KeyTextField;

  /**
   * title field in *AlternateGrid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *AlternateGrid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *AlternateGrid → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *AlternateGrid → Items*
 */
export interface AlternateGridSliceDefaultItem {
  /**
   * title field in *AlternateGrid → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *AlternateGrid → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for AlternateGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternateGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AlternateGridSliceDefaultPrimary>,
  Simplify<AlternateGridSliceDefaultItem>
>;

/**
 * Primary content in *AlternateGrid → Primary*
 */
export interface AlternateGridSliceImageRightPrimary {
  /**
   * eyebrowHeadline field in *AlternateGrid → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: alternate_grid.primary.eyebrowHeadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrowHeadline: prismic.KeyTextField;

  /**
   * title field in *AlternateGrid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *AlternateGrid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *AlternateGrid → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *AlternateGrid → Items*
 */
export interface AlternateGridSliceImageRightItem {
  /**
   * title field in *AlternateGrid → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *AlternateGrid → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Image Right variation for AlternateGrid Slice
 *
 * - **API ID**: `imageRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternateGridSliceImageRight = prismic.SharedSliceVariation<
  "imageRight",
  Simplify<AlternateGridSliceImageRightPrimary>,
  Simplify<AlternateGridSliceImageRightItem>
>;

/**
 * Slice variation for *AlternateGrid*
 */
type AlternateGridSliceVariation =
  | AlternateGridSliceDefault
  | AlternateGridSliceImageRight;

/**
 * AlternateGrid Shared Slice
 *
 * - **API ID**: `alternate_grid`
 * - **Description**: AlternateGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternateGridSlice = prismic.SharedSlice<
  "alternate_grid",
  AlternateGridSliceVariation
>;

/**
 * Default variation for Frame Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FrameSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Frame*
 */
type FrameSliceVariation = FrameSliceDefault;

/**
 * Frame Shared Slice
 *
 * - **API ID**: `frame`
 * - **Description**: Frame
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FrameSlice = prismic.SharedSlice<"frame", FrameSliceVariation>;

/**
 * Primary content in *List → Items*
 */
export interface ListSliceDefaultItem {
  /**
   * siggahl field in *List → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: list.items[].siggahl
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  siggahl: prismic.ContentRelationshipField<"sigga">;
}

/**
 * Default variation for List Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ListSliceDefaultItem>
>;

/**
 * Primary content in *List → Items*
 */
export interface ListSliceRannsoknItem {
  /**
   * siggahl field in *List → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: list.items[].siggahl
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  siggahl: prismic.ContentRelationshipField<"rannsoknir">;
}

/**
 * rannsokn variation for List Slice
 *
 * - **API ID**: `rannsokn`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ListSliceRannsokn = prismic.SharedSliceVariation<
  "rannsokn",
  Record<string, never>,
  Simplify<ListSliceRannsoknItem>
>;

/**
 * Primary content in *List → Items*
 */
export interface ListSliceSiggaItem {
  /**
   * siggahl field in *List → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: list.items[].siggahl
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  siggahl: prismic.ContentRelationshipField<"sigga">;
}

/**
 * sigga variation for List Slice
 *
 * - **API ID**: `sigga`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ListSliceSigga = prismic.SharedSliceVariation<
  "sigga",
  Record<string, never>,
  Simplify<ListSliceSiggaItem>
>;

/**
 * Primary content in *List → Items*
 */
export interface ListSliceSkipulagItem {
  /**
   * siggahl field in *List → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: list.items[].siggahl
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  siggahl: prismic.ContentRelationshipField<"skipulagsradgjof">;
}

/**
 * skipulag variation for List Slice
 *
 * - **API ID**: `skipulag`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ListSliceSkipulag = prismic.SharedSliceVariation<
  "skipulag",
  Record<string, never>,
  Simplify<ListSliceSkipulagItem>
>;

/**
 * Slice variation for *List*
 */
type ListSliceVariation =
  | ListSliceDefault
  | ListSliceRannsokn
  | ListSliceSigga
  | ListSliceSkipulag;

/**
 * List Shared Slice
 *
 * - **API ID**: `list`
 * - **Description**: List
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ListSlice = prismic.SharedSlice<"list", ListSliceVariation>;

/**
 * Primary content in *ListSlice → Items*
 */
export interface ListSliceSliceDefaultItem {
  /**
   * Link field in *ListSlice → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: list_slice.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.ContentRelationshipField;
}

/**
 * Default variation for ListSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ListSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ListSliceSliceDefaultItem>
>;

/**
 * Slice variation for *ListSlice*
 */
type ListSliceSliceVariation = ListSliceSliceDefault;

/**
 * ListSlice Shared Slice
 *
 * - **API ID**: `list_slice`
 * - **Description**: ListSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ListSliceSlice = prismic.SharedSlice<
  "list_slice",
  ListSliceSliceVariation
>;

/**
 * Default variation for Tekki Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TekkiSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Tekki*
 */
type TekkiSliceVariation = TekkiSliceDefault;

/**
 * Tekki Shared Slice
 *
 * - **API ID**: `tekki`
 * - **Description**: Tekki
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TekkiSlice = prismic.SharedSlice<"tekki", TekkiSliceVariation>;

/**
 * Primary content in *TextS → Items*
 */
export interface TextSSliceDefaultItem {
  /**
   * teksti field in *TextS → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_s.items[].teksti
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  teksti: prismic.RichTextField;

  /**
   * mynd field in *TextS → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_s.items[].mynd
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  mynd: prismic.ImageField<never>;

  /**
   * embed field in *TextS → Items*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: text_s.items[].embed
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  embed: prismic.EmbedField;

  /**
   * meida field in *TextS → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: text_s.items[].meida
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  meida: prismic.LinkToMediaField;
}

/**
 * Default variation for TextS Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<TextSSliceDefaultItem>
>;

/**
 * Slice variation for *TextS*
 */
type TextSSliceVariation = TextSSliceDefault;

/**
 * TextS Shared Slice
 *
 * - **API ID**: `text_s`
 * - **Description**: TextS
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSSlice = prismic.SharedSlice<"text_s", TextSSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSigganavItem,
      HomeDocumentDataSkipulagsNavItem,
      HomeDocumentDataRannsoknirItem,
      HomeDocumentDataSlicesSlice,
      MainnavDocument,
      MainnavDocumentData,
      MainnavDocumentDataEgveitekkertItem,
      RannsoknirDocument,
      RannsoknirDocumentData,
      RannsoknirDocumentDataSlicesSlice,
      SiggaDocument,
      SiggaDocumentData,
      SiggaDocumentDataSlicesSlice,
      SkipulagsradgjofDocument,
      SkipulagsradgjofDocumentData,
      SkipulagsradgjofDocumentDataSlicesSlice,
      AllDocumentTypes,
      AlternateGridSlice,
      AlternateGridSliceDefaultPrimary,
      AlternateGridSliceDefaultItem,
      AlternateGridSliceImageRightPrimary,
      AlternateGridSliceImageRightItem,
      AlternateGridSliceVariation,
      AlternateGridSliceDefault,
      AlternateGridSliceImageRight,
      FrameSlice,
      FrameSliceVariation,
      FrameSliceDefault,
      ListSlice,
      ListSliceDefaultItem,
      ListSliceRannsoknItem,
      ListSliceSiggaItem,
      ListSliceSkipulagItem,
      ListSliceVariation,
      ListSliceDefault,
      ListSliceRannsokn,
      ListSliceSigga,
      ListSliceSkipulag,
      ListSliceSlice,
      ListSliceSliceDefaultItem,
      ListSliceSliceVariation,
      ListSliceSliceDefault,
      TekkiSlice,
      TekkiSliceVariation,
      TekkiSliceDefault,
      TextSSlice,
      TextSSliceDefaultItem,
      TextSSliceVariation,
      TextSSliceDefault,
    };
  }
}
