// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  alternate_grid: dynamic(() => import("./AlternateGrid")),
  frame: dynamic(() => import("./Frame")),
  list: dynamic(() => import("./List")),
  text_s: dynamic(() => import("./TextS")),
};
